version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_base
    ports:
      - 3308:3306
  server:
    image: suttyread/react-server
    ports:
      - '9000:9000'
    expose:
      - '9000'
  client:
    image: suttyread/react-client
    ports:
      - '3000:3000'
    expose:
      - '3000'